/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hahnentt_rd_jni_NativeInspector */

#ifndef _Included_com_hahnentt_rd_jni_NativeInspector
#define _Included_com_hahnentt_rd_jni_NativeInspector
#ifdef __cplusplus
extern "C" {
#endif
  /*
   * Class:     com_hahnentt_rd_jni_NativeInspector
   * Method:    listExportedJniMethodsNative
   * Signature: (Ljava/lang/String;)[Ljava/lang/String;
   */
  JNIEXPORT jobjectArray JNICALL Java_com_hahnentt_rd_jni_NativeInspector_listExportedJniMethodsNative(JNIEnv*, jclass,
      jstring);

#ifdef __cplusplus
}
#endif
#endif
